begin transaction;

create table users (
    auth_provider int check (auth_provider between 0 and 1),
    id bigint generated by default as identity,
    email varchar(255),
    hash varchar(255),
    name varchar(255),
    oauth_id varchar(255) unique,
    role varchar(8) check (role in ('ADMIN', 'MEMBER', 'OWNER')),
    primary key (id)
);

create table hotels (
    rating float(53) not null,
    id bigint generated by default as identity,
    lat bigint not null,
    lng bigint not null,
    owner bigint,
    description varchar(255),
    name varchar(255),
    primary key (id)
);

create table reviews (
    rating integer not null,
    hotel_id bigint not null,
    user_id bigint not null,
    text varchar(255),
    primary key (hotel_id, user_id)
);

end transaction;